;; -*- mode: eask; lexical-binding: t -*-

(package "jai-mode"
         "0.1.0"
         "Major mode for JAI")

(website-url "https://github.com/elp-revive/jai-mode")
(keywords "languages")

(package-file "jai-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
